openapi: 3.0.0
info:
  title: API de gestión de médicos
  description: Esta es una API para gestionar médicos en una aplicación de reserva de citas médicas online.
  version: 1.0.0

servers:
  - url: https://localhost

tags:
  - name: Gestión de médicos
    description: Todos los servicios relacionados con la gestión de médicos.

paths:
  /ux-gestion-medicos/sm_health/servicio-al-cliente/v1/consultar-medicos:
    get:
      tags:
        - Gestión de médicos
      summary: Consultar todos los médicos
      security:
        - gesticon_auth: [read:gesticon]
      responses:
        '200':
          description: Una lista de médicos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Medico'

  /ux-gestion-medicos/sm_health/servicio-al-cliente/v1/consultar-medico/{idMedico}:
    get:
      tags:
        - Gestión de médicos
      summary: Consultar un médico específico
      security:
        - gesticon_auth: [read:gesticon]
      parameters:
        - in: path
          name: idMedico
          required: true
          schema:
            type: integer
          description: Identificador único del médico
      responses:
        '200':
          description: Un médico específico
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medico'

  /ux-gestion-medicos/sm_health/servicio-al-cliente/v1/consultar-medicos-favoritos/{idUsuario}:
    get:
      tags:
        - Gestión de médicos
      summary: Consultar los médicos favoritos de un usuario
      security:
        - gesticon_auth: [read:gesticon]
      parameters:
        - in: path
          name: idUsuario
          required: true
          schema:
            type: integer
          description: Identificador único del usuario
      responses:
        '200':
          description: Una lista de médicos favoritos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Medico'

  /ux-gestion-medicos/sm_health/servicio-al-cliente/v1/asignar-medico-favorito/{idUsuario}:
    put:
      tags:
        - Gestión de médicos
      summary: Asignar un médico favorito a un usuario
      security:
        - gesticon_auth: [write:gesticon]
      parameters:
        - in: path
          name: idUsuario
          required: true
          schema:
            type: integer
          description: Identificador único del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Medico'
      responses:
        '200':
          description: El médico se asignó como favorito correctamente

components:
  schemas:
    Medico:
      type: object
      properties:
        idMedico:
          type: integer
          example: 1
        nombreMedico:
          type: string
          example: Dr. Juan Pérez
        especialidad:
          type: string
          example: Cardiología

  securitySchemes:
    gesticon_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://gesticon.swagger.io/oauth/authorize
          scopes:
            write:gesticon: Modificar gesticon en tu cuenta
            read:gesticon: Leer tu gesticon
    api_key:
      type: apiKey
      name: api_key
      in: header