openapi: 3.0.0
info:
  title: API de gestión de especialidades
  description: Esta es una API para gestionar las especialidades en una aplicación de reserva de citas médicas online.
  version: 1.0.0

servers:
  - url: https://localhost

tags:
  - name: Gestión de especialidades
    description: Todos los servicios relacionados con la gestión de especialidades.

paths:
  /ux-gestion-especialidades/the_cure/servicio-al-cliente/v1/consultar-especialidades:
    get:
      tags:
        - Gestión de especialidades
      summary: Consultar todas las especialidades
      security:
        - gesticon_auth: [read:gesticon]
      responses:
        '200':
          description: Una lista de especialidades
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Especialidad'

  /ux-gestion-especialidades/the_cure/servicio-al-cliente/v1/consultar-especialidades/{idClinica}:
    get:
      tags:
        - Gestión de especialidades
      summary: Consultar especialidades de una clínica específica
      security:
        - gesticon_auth: [read:gesticon]
      parameters:
        - in: path
          name: idClinica
          required: true
          schema:
            type: integer
          description: Identificador único de la clínica
      responses:
        '200':
          description: Una lista de especialidades
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Especialidad'

  /ux-gestion-especialidades/the_cure/servicio-al-cliente/v1/consultar-especialidades-favoritas/{idUsuario}:
    get:
      tags:
        - Gestión de especialidades
      summary: Consultar las especialidades favoritas de un usuario
      security:
        - gesticon_auth: [read:gesticon]
      parameters:
        - in: path
          name: idUsuario
          required: true
          schema:
            type: integer
          description: Identificador único del usuario
      responses:
        '200':
          description: Una lista de especialidades favoritas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Especialidad'

  /ux-gestion-especialidades/the_cure/servicio-al-cliente/v1/asignar-especialidades-favoritas/{idUsuario}:
    put:
      tags:
        - Gestión de especialidades
      summary: Asignar una especialidad favorita a un usuario
      security:
        - gesticon_auth: [write:gesticon]
      parameters:
        - in: path
          name: idUsuario
          required: true
          schema:
            type: integer
          description: Identificador único del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Especialidad'
      responses:
        '200':
          description: La especialidad se asignó como favorita correctamente

components:
  schemas:
    Especialidad:
      type: object
      properties:
        idEspecialidad:
          type: integer
          example: 1
        nombreEspecialidad:
          type: string
          example: Cardiología
        descripcionEspecialidad:
          type: string
          example: Tratamiento y diagnóstico de enfermedades del corazón.

  securitySchemes:
    gesticon_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://gesticon.swagger.io/oauth/authorize
          scopes:
            write:gesticon: Modificar gesticon en tu cuenta
            read:gesticon: Leer tu gesticon
    api_key:
      type: apiKey
      name: api_key
      in: header